volumes:
  caddy_data:
  caddy_config:
services:
  caddy:
    image: "caddy:2.9"
    restart: unless-stopped 
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 80:80/udp
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  stream:
    image: hear-stream:latest
    environment:
      SERVER_PORT: 3000
      SERVER_REDIRECT_URL: http://streambot:3000/authorize
      TWITCH_CLIENT_ID: mueydej92p86hxi1lq00omzhqztbw6
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      TWITCH_BROADCASTER_ID: 161697677
      TWITCH_BROADCASTER_NAME: memtooth
      TWITCH_BOT_ID:
      TWITCH_BOT_NAME: sennx
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://streambot:3000/.well-known/healthcheck"]
      interval: 3s
      timeout: 8s
      retries: 5